### PR TITLE
Support Android 12 & latest Frida

### PR DESCRIPTION
**Pull request by enovella**

### CODE REVIEW

**Comment by ViRb3** [comment]
Are you certain that this build prop exists on all ROMs? I totally get the idea, but if some manufacturer or custom ROM doesn't set this build prop, then frida will never run at all.

**Comment by enovella** [comment]
Good point, but I believe that this build property belongs to the AOSP codebase, especially the core part (https://source.android.com/devices/tech/perf/boot-times & https://android.googlesource.com/platform/system/core/+/master/rootdir/init.rc).

**Comment by enovella** [comment]
@ViRb3 This ticket was related to the same bug https://github.com/frida/frida/issues/1225. Not sure if you included this fix after this or not.

**Comment by Manouchehri** [comment]
Running into this issue as well.

**Comment by ViRb3** [comment]
Sorry guys, this PR slipped through me somehow. What is the situation now? Any fixes from Frida itself? Is this still happening on Android 12? I'm still worried about devices which don't have this build prop, because then Frida will never be loaded. @enovella could you please check if the build prop is set to 0 before it's set to 1? If that's the case, we can only activate the waiting logic if the property exists, not impacting any devices without it.

**Comment by enovella** [comment]
Hi guys,

Tested on Samsung, OnePlus, Xiaomi and Google Pixel devices and having this flag on all the ROMs.

**Comment by enovella** [comment]
@Manouchehri Which devices were you working on? Did my MR work out on your end?  Regards mate.

**Comment by enovella** [comment]
@ViRb3 This is the order

```sh
$ while true; do adb shell getprop sys.boot_completed; sleep 0.5;done
...
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
1
1
1
1
1
1
1
1
```

**Comment by enovella** [comment]
@ViRb3 Check this out https://github.com/frida/frida/issues/1225

**Comment by Manouchehri** [comment]
> @Manouchehri Which devices were you working on? Did my MR work out on your end?  Regards mate.

@enovella Sorry, I don't think I've tried your patch yet. 😅 I just remember running into the issue, and my "workaround" was to launch Frida manually myself after boot with adb.

**Comment by enovella** [comment]
> > @Manouchehri Which devices were you working on? Did my MR work out on your end?  Regards mate.
> 
> @enovella Sorry, I don't think I've tried your patch yet. sweat_smile I just remember running into the issue, and my "workaround" was to launch Frida manually myself after boot with adb.

okay, no rush. Let us know when you've tested it.

**Comment by ViRb3** [comment]
Any changes here? At this point, I am willing to risk and merge this and see if people complain of broken Frida or not. Hopefully not :)

**Comment by enovella** [comment]
ETA?

**Comment by ViRb3** [comment]
Done. Please let me know if everything still works.

**Comment by enovella** [comment]
@ViRb3 Something went wrong with the double loop. However, I am developing another Magisk module and no have issues with Frida and Android 9/10/11/12.

```sh
[16:30 edu@xps ~] >  frida-ps -aUi
Failed to enumerate applications: unable to find process with name 'system_server'
[16:34 edu@xps ~] >  frida-ps -aUi
Failed to enumerate applications: unable to find process with name 'system_server'
[16:34 edu@xps ~] >  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
```

```sh
[17:54 edu@xps ~] >  adb shell su -c which frida-server
/system/bin/frida-server
[17:54 edu@xps ~] >  adb shell su -c ps -A | grep frida
root          3273     1 10918340 50340 do_sys_poll         0 S frida-server
root          3839  1723 10916976  3868 do_sys_poll         0 S frida-server
root          3844  3839       0      0 0                   0 Z [frida-server]
[17:54 edu@xps ~] >  frida-ps -Uai
Failed to enumerate applications: timeout was reached 
```

**Comment by enovella** [comment]
```sh
[18:27 edu@xps ~] >  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[18:27 edu@xps ~] >  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[18:27 edu@xps ~] >  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[18:27 edu@xps ~] >  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[18:27 edu@xps ~] >  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[18:28 edu@xps ~] >  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[18:28 edu@xps ~] >  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[18:28 edu@xps ~] >  adb shell su -c which frida-server
/system/bin/frida-server
[18:28 edu@xps ~] >  adb shell su -c ps -A | grep frida
root          3569     1 10900908 51204 do_sys_poll         0 S frida-server
root          4681  1814 10873968  4340 do_sys_poll         0 S frida-server
root          4682  4681       0      0 0                   0 Z [frida-server]
root          4761     1   23408   3568 do_sys_poll         0 S frida-helper-32
[18:28 edu@xps ~] >  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[18:28 edu@xps ~] >  adb shell 
sunfish:/data/adb/modules/magisk-frida # /data/adb/magisk/busybox vi service.sh                                                                              
sunfish:/data/adb/modules/magisk-frida # reboot                                                                                                              
[18:30 edu@xps ~] >  adb shell su -c ps -A | grep frida
root          3309     1 10940776 10396 0                   0 R frida-server
root          4455     1   23408   2040 do_sys_poll         0 S frida-helper-32
[18:32 edu@xps ~] >  frida-ps -Uai
  PID  Name                          Identifier                             
-----  ----------------------------  ---------------------------------------
10234  Any.do                        com.anydo                              
11346  Calendar                      com.google.android.calendar            
 8400  Contacts                      com.google.android.contacts            
11427  Gmail                         com.google.android.gm                  
 3788  Google                        com.google.android.googlequicksearchbox
 4896  Google Play Store             com.android.vending                    
10391  Guidelines                    com.esccardio.escpocketguidelines      
10649  Magisk                        com.topjohnwu.magisk                   
10561  Maps                          com.google.android.apps.maps           
 3434  Messages                      com.google.android.apps.messaging      
10467  NowSecure Workstation Agent   com.viaforensics.androidagent          
11167  Phone                         com.google.android.dialer              
10829  Photos                        com.google.android.apps.photos         
11572  Settings                      com.android.settings                   
10506  WireGuard                     com.wireguard.android                  
 9701  YouTube                       com.google.android.youtube             
10928  YouTube Music                 com.google.android.apps.youtube.music  
    -  1Password                     com.agilebits.onepassword              
    -  Amazon Shopping               com.amazon.mShop.android.shopping    
  ```

**Comment by enovella** [comment]
sunfish:/data/adb/modules/magisk-frida # cat service.sh     

```sh                                                                                                 
#!/system/bin/sh
# Do NOT assume where your module will be located.
# ALWAYS use $MODDIR if you need to know where this script
# and module is placed.
# This will make sure your module will still work
# if Magisk change its mount point in the future
MODDIR=${0%/*}

# This script will be executed in late_start service mode
while [ "$(getprop sys.boot_completed)" != 1 ]; do
    sleep 1
done

sleep 5 && frida-server -D
```

**Comment by ViRb3** [comment]
@enovella Hmm, I find it impossible to believe that it's the loop at fault. I am pretty sure it's the extra delay that fixed it. I added `sleep 5` in [this commit](https://github.com/ViRb3/magisk-frida/commit/8471e0796723fc6d9692f171db9447c8ae0fda14) and made a release, please test it.

**Comment by enovella** [comment]
It doesnt work. 


```sh
[11:37 edu@xps ]  (master)>  frida-ps -Uai
 PID  Name                          Identifier                             
----  ----------------------------  ---------------------------------------
3959  Android Auto                  com.google.android.projection.gearhead 
4572  Chrome                        com.android.chrome                     
4672  Clock                         com.google.android.deskclock           
3720  Google                        com.google.android.googlequicksearchbox
3410  Messages                      com.google.android.apps.messaging      
2728  Settings                      com.android.settings                   
3829  YouTube                       com.google.android.youtube             
3823  YouTube Music                 com.google.android.apps.youtube.music  
   -  1Password                     com.agilebits.onepassword              
   -  Amazon Shopping               com.amazon.mShop.android.shopping      
   -  Any.do                        com.anydo                              
   -  BOI Mobile                    com.bankofireland.mobilebanking        
   -  BRD                           com.breadwallet                        
   -  Badoo                         com.badoo.mobile                       
   -  Bank Austria                  com.bankaustria.android.olb            
   -  Bank of Scot                  com.grppl.android.shell.BOS            
   -  Bitdefender VPN               com.bitdefender.vpn                    
   -  Bumble                        com.bumble.app                         
   -  CONGA 4000                    es.cecotec.s4090                       
   -  Calculator                    com.google.android.calculator          
   -  Calendar                      com.google.android.calendar            
   -  Camera                        com.google.android.GoogleCamera        
   -  Capitec                       capitec.acuity.mobile.prod             
   -  Cards                         com.cardsapp.android                   
   -  Carteira Digital de Trânsito  br.gov.serpro.cnhe                     
   -  CoinPayments                  net.coinpayments.coinpaymentsapp       
   -  Connect IQ                    com.garmin.connectiq                   
   -  Contacts                      com.google.android.contacts            
   -  DSDefender VPN                com.blindcut.dsdefender.vpn            
   -  Drive                         com.google.android.apps.docs           
   -  DuckDuckGo                    com.duckduckgo.mobile.android          
   -  EVO Banco                     es.evobanco.bancamovil                 
   -  Ecobank                       com.app.ecobank                        
   -  Ethereum                      eth.org.freewallet.app                 
   -  ExpressVPN                    com.expressvpn.vpn                     
   -  F-Secure KEY                  com.fsecure.key                        
   -  Files by Google               com.google.android.apps.nbu.files      
   -  GigaTV                        qa.vodafone.tv.proda                   
   -  GitHub                        com.github.android                     
   -  Global Card Access            com.bofaenterprise.gca.mobile          
   -  Glovo                         com.glovo                              
   -  Gmail                         com.google.android.gm                  
   -  Google Play Store             com.android.vending                    
   -  Google TV                     com.google.android.videos              
   -  Guidelines                    com.esccardio.escpocketguidelines      
   -  Magisk                        com.topjohnwu.magisk                   
   -  Maps                          com.google.android.apps.maps           
   -  McDonald's                    com.mcdonalds.mobileapp                
   -  NowSecure Workstation Agent   com.viaforensics.androidagent          
   -  Personal Safety               com.google.android.apps.safetyhub      
   -  Phone                         com.google.android.dialer              
   -  Photos                        com.google.android.apps.photos         
   -  Pixel Tips                    com.google.android.apps.tips           
   -  Recorder                      com.google.android.apps.recorder       
   -  The Crypto App                com.crypter.cryptocyrrency             
   -  Uncrackable1                  sg.vantagepoint.uncrackable1           
   -  Vysor                         com.koushikdutta.vysor                 
   -  WireGuard                     com.wireguard.android                  
   -  ePayments                     clientapp.swiftcom.org                 
   -  eToro                         com.etoro.openbook                     
   -  eToro Money                   com.etoro.wallet                       
[11:37 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:37 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:37 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:37 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:37 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:38 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:38 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:38 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:38 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:38 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:38 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:38 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:38 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
[11:38 edu@xps ]  (master)>  frida-ps -Uai
Failed to enumerate applications: unable to find process with name 'system_server'
```

**Comment by enovella** [comment]
This is what your fix does:
```sh
[11:43 edu@xps]  (master)>  adb shell su -c ps -A | grep frida
root          4178     1 10919340 50432 do_sys_poll         0 S frida-server
root          4541  1828 10863728  4060 do_sys_poll         0 S frida-server
root          4543  4541       0      0 0                   0 Z [frida-server]
root          4718     1   23408   3068 do_sys_poll         0 S frida-helper-32
```

**Comment by ViRb3** [comment]
Yikes.... I just spotted a very significant issue:
```
frida-server -D
```
From docs:
```
-D, --daemonize                       Detach and become a daemon
```
We are basically restarting the daemon over and over, since it never blocks. Could you please test if the same Magisk module without the `-D` flag works? That was the intended way anyway.

**Comment by enovella** [comment]
@ViRb3 Choose one. Both work well. I'd prefer the daemon, but as you wish. The delay of 5 secs is unclear if required. A bug with Magisk/Frida is that in Google devices the camera crashes with Magisk-Frida. I've seen that on Android 11/12 so far.

```sh
# restart on crash
while true; do
    frida-server
    sleep 1
done
```

```sh
# restart on crash
frida-server -D
```

**Comment by ViRb3** [comment]
I pulled out my old Android phone and ran a thorough test as well. Removing the `-D` flag and keeping the second loop works good. Killing the server (simulating a crash) then properly restarts it:

```
dumpling:/ # pidof frida-server
7544
dumpling:/ # pkill frida-server
dumpling:/ # pidof frida-server
1|dumpling:/ # pidof frida-server
7594
dumpling:/ #
```

If I remove the loop and keep the `-D` flag, then killing the server does not restart it:
```
dumpling:/ # pidof frida-server
3699
dumpling:/ # pkill frida-server
dumpling:/ # pidof frida-server
1|dumpling:/ # pidof frida-server
1|dumpling:/ # pidof frida-server
1|dumpling:/ # pidof frida-server
```

I think I definitely prefer the auto-restart approach, since otherwise you have to reboot your phone if something happens to Frida.

I will leave the 5 seconds delay just in case, it doesn't hurt since it only happens once during early boot. Does Camera crash even with the 5 second delay? I thought that fixed it.

Thanks a lot for the help with tracking this down, I do not currently use Android and this was a nasty bug that sneaked in.

**Comment by ViRb3** [comment]
@enovella I just released 15.1.14-4, but in Magisk Manager the latest one is 15.1.14-1. Seems like none of the patch releases are being shown. This is weird, because I definitely both the `version` and `versionCode`: https://github.com/Magisk-Modules-Repo/magisk-frida/commit/2c338de7dbef9503c33b2729e638ba3b4c2c244d. I remember some changes coming to Magisk repo, has it been deprecated?

**Pull request merged**
