### PR TITLE
Update module to support Magisk 24

### LINKED ISSUE #20: Rework project due to Magisk 24 changes
Release notes:
https://github.com/topjohnwu/Magisk/releases/tag/v24.0

Highlights:
- Magisk-Modules-Repo frozen
- Module format changed, with `updateJson` added

Plan:
1. ~~Rework CI to use GItHub Actions~~ (done)
2. ~~Proper releases in GitHub (no pre-release)~~ (done)
3. Update to new module format
4. Add new update mechanic using `updateJson`

### PR DESCRIPTION
**Pull request by freyta**
This automatically creates an update.json file which Magisk should check for updates.

I removed the use of the NEW_TAG.txt file to set the environmental variable, and instead use the main Python script. I also have set a few other variables which are used to write the JSON file such as which GitHub repository runs the action, and if none is set then it doesn't write a update URL to the module.prop.

Should fix #20

### CODE REVIEW

**Comment by freyta** [comment]
Any progress on this?

**Comment by ViRb3** [comment]
Sorry, I've been very busy and haven't had the time to test it yet. I'll try to do this at the end of this week.

**Comment by freyta** [comment]
Still no updates on this? 

Can you explain how you get [MagiskFridaBot](https://github.com/MagiskFridaBot) to trigger the build process please? I can't seem to find any information on it.

**Comment by ViRb3** [comment]
My apologies again for the constant delays. This task was very low priority for me and kept getting pushed back. I wanted to refactor the code so it doesn't commit the `updater.json` every time but never got the time for it. Since #37 was released with exactly that, I merged it in favor of this PR. Auto updates should work finally.

Regarding the triggering of this pipeline, it's hooked directly into magisk project from their side.

**Pull request closed without merging**
