### PR TITLE
Supports Android 10 & fix unzip on ROMs without unzip

### PR DESCRIPTION
**Pull request by enovella**

### CODE REVIEW

**Comment by enovella** [comment]
FYI - Frida v12.8.15 onwards fixes the [issue](https://github.com/frida/frida-core/commit/e4f7651286be48528d143b33d946d313f305ed2a) of the helper on Android 10.

**Comment by ViRb3** [comment]
Your PR looks great, just not sure about installing `frida-server` to `bin` instead of `xbin` - the former should be used by required AOSP binaries only, while the latter contains "extra" programs like Frida, according to [this StackOverflow answer](https://stackoverflow.com/questions/26801895/the-different-between-android-foldersbin-xbin-sbin/26802239). Does the latest Frida version work from `xbin` again, or am I misunderstanding?

**Comment by enovella** [comment]
This post was asked 5 years, 4 months ago.

I dont see any folder with `xbin` on Android 9 & 10. Dont recall it working using this folder.

**Comment by ViRb3** [comment]
Interesting, `/xbin` doesn't exist but `/system/xbin` exists on my OnePlus 5T running Android 9 LineageOS, and it contains extra utilities like `zip`. Can you please confirm if `/system/xbin` definitely doesn't exist for you? It's not a problem to use `bin`, I was just trying to keep the convention (if one exists).

**Comment by enovella** [comment]
Google Pixel3a & Android 10
```sh
sargo:/ # cd /system/                                                                                                                  
apex/       bin/        etc/        framework/  lib64/      product/    vendor/
app/        build.prop  fonts/      lib/        priv-app/   usr/
```

**Comment by ViRb3** [comment]
Well, `bin` it will be then. Thanks for the help!

**Pull request merged**
